### 탈퇴 api
DELETE {{url}}/member/resign
memberId:1

### 수정 api
PATCH {{url}}/member
memberId:1
Content-Type: application/json

{
  "nickname": "newNickname"
}

### 리스트 조회 api
GET {{url}}/member?page=0&size=2
